# Linear Regression with Numpy
In this tutorial we demonstrate the functionalities of Numpy by doing an exercise on Linear Regression. The datasets are randomly generated. We use the ordinary least squares method to obtain the optimal parameters.

In [4]:
import numpy as np

We start by constructing a random dataset `X`.
The variable `X` is of the type `numpy.ndarray`, which is the central datatype
for numpy calculations. Next, we will explore the attributes and methods provided by this datatype, along with
other functions present in numpy package

In [10]:
X = np.random.uniform(size=(1000,10))
type(X)

numpy.ndarray

The attribute `shape` gives the size of the `numpy.ndarray` object, per axis. To get the transpose of the matrix, we can simply do `X.T`

In [6]:
X.shape, X.T.shape

((1000, 10), (10, 1000))

`numpy` allows easy indexing and slicing of the matrix, by providing the range of the indices. For multidimensional indexing, we can use Matlab like notation: `X[4,3]`. But unlike Matlab, the first index
of any `numpy` array is 0.

In [9]:
print(X[2:4, -5:-1])

[[  1.24210388e-01   2.88602157e-01   2.33376277e-01   8.69433605e-01]
 [  6.07982050e-01   7.34809681e-01   3.71530411e-04   4.64793300e-01]]


In [21]:
print(X[2:4, :])

[[ 0.25267011  0.22103237  0.49239966  0.8666039   0.57544191  0.23426442
   0.8179003   0.68621908  0.78174368  0.64364756]
 [ 0.72127757  0.95189444  0.54134705  0.36909941  0.30658017  0.51168315
   0.8858587   0.39777026  0.51782958  0.26846217]]


We already saw one way of creating an `ndarray` object. There are some more ways of creating `ndarray` objects:

`np.eye(size)` creates an identity matrix of size `size`.

In [16]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

We can also create an `ndarray` object filled with the same scalar value using `np.full`

In [17]:
np.full([2,3], 2.0)

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

If we want to change the shape of our matrix, we can use the `reshape` method. We can skip the size for the first or the last dimension (but not both), since the product of the sizes of all the dimensions combined should
be the same before and after `reshape()`

In [20]:
X.reshape([-1, 2])

array([[ 0.95395731,  0.83222084],
       [ 0.94842382,  0.66444619],
       [ 0.27869962,  0.3121831 ],
       ..., 
       [ 0.62564943,  0.7603501 ],
       [ 0.61326095,  0.66314223],
       [ 0.23612487,  0.87628573]])

## Linear Regression

We will now implement a linear regression model to quantify the relationship between `Y` and `X`. To do this, we start by creating synthetic `X` and `Y`. Remember, in real world problems, we are generally provide with `Y` and `X`. Since this a playground exercise, we will create them synthetically using some randomly initialized `weights_`. Then we will try to estimate `W` using the analytical solution derived in the class and demonstrate its closeness to the actual `weights_` which generated the data

In [19]:
weights_ = np.random.normal(0, 1, size=[10])
bias_ = np.random.normal(0, 1, size=1)
weights_.shape, bias_.shape

((10,), (1,))

In [20]:
Y = np.dot(X, weights_) + bias_

The first step is to create the augmented matrix `X_aug`. This is achieved by prepending a column of 1s to the matrix `X`

In [24]:
one_column = np.full([X.shape[0], 1], 1)
one_column.shape

(1000, 1)

To append matrices horizontally or vertically, we use `hstack` and `vstack` functions in `numpy` package. The appended matrices should have corresponding dimensions matching in size.

In [25]:
X_aug = np.hstack([one_column, X])
X_aug

array([[  1.00000000e+00,   7.92170718e-01,   1.14055071e-01, ...,
          7.78788648e-01,   9.01971904e-01,   1.67425136e-01],
       [  1.00000000e+00,   2.24040281e-01,   5.04284249e-01, ...,
          1.33903145e-01,   2.94464314e-01,   1.10787600e-02],
       [  1.00000000e+00,   2.52670113e-01,   2.21032374e-01, ...,
          6.86219076e-01,   7.81743684e-01,   6.43647562e-01],
       ..., 
       [  1.00000000e+00,   3.10102717e-01,   1.62708252e-01, ...,
          2.54852533e-01,   2.20784155e-01,   7.54477451e-01],
       [  1.00000000e+00,   4.95994903e-01,   9.80665589e-01, ...,
          5.00026006e-01,   4.82723227e-01,   6.22462036e-01],
       [  1.00000000e+00,   7.68896246e-01,   4.68451416e-04, ...,
          2.26746708e-01,   1.08470727e-01,   4.59755409e-01]])

To multiply two matrices, we can't use the `*` operator, since it will multiply the matrices elementwise. Here's an example to show that

In [26]:
np.full([3,3], 2) * np.eye(3)

array([[ 2.,  0.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  2.]])

Instead we use `np.dot`, which multiplies the matrices as we know it from mathematics. Now, from the formula, the part we are missing is to calculate the inverse, which can be done via `np.linalg.inv`.

`np.linalg` is a sub-package within `numpy` which provides some of the useful linear algebra operations. Other examples of linear algebra operations are:
- determinant calculation
- eigen value decomposition
- cholesky decomposition
- trace

and so on..

In [46]:
W = np.dot(np.dot(np.linalg.inv(np.dot(X_aug.T, X_aug)), X_aug.T), Y)

Finally we have our estimated weights `W` for the linear regression model. We can now compare it against original `weights_` to see how well it performs.

In [32]:
bias_

array([ 0.0486995])

In [35]:
weights_

array([ 0.97846304, -0.62400473, -1.18757892, -0.0727091 ,  1.34215761,
        1.30466299,  0.05013723, -1.21192935,  0.25199518, -0.42339918])

In [49]:
W - np.hstack([bias_, weights_]) < 1e-6

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)